// src/routes/prayer.ics/+server.ts

import type { RequestHandler } from '@sveltejs/kit';
import { buildIcsCalendar, type IcsEventConfig } from '$lib/ics';

// Config: adjust times or summaries here.
// Times are in UTC. Example below:
// 2025-01-01 11:00–11:20 UTC = 6:00–6:20 AM in Miami (EST).
const prayerEvents: IcsEventConfig[] = [
	{
		uid: 'manna-prayer-daily-1',
		start: '20250101T110000Z',
		end: '20250101T112000Z',
		summary: 'Manna Daily Prayer',
		description: 'Daily prayer anchor generated by Manna.',
		rrule: 'FREQ=DAILY'
	}
];

const ICS_BODY = buildIcsCalendar({
	prodId: '-//Manna//Prayer Calendar//EN',
	events: prayerEvents
});

export const GET: RequestHandler = () => {
	return new Response(ICS_BODY, {
		headers: {
			'Content-Type': 'text/calendar; charset=utf-8',
			'Content-Disposition': 'attachment; filename="prayer.ics"',
			'Cache-Control': 'public, max-age=300',
			'X-Robots-Tag': 'noindex, nofollow'
		}
	});
};
